---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: suppliers
  label: Suppliers
  create: documents
  match: "**/*"
  exclude: "**/index.md"
  new_doc_ext: md
  templates:
  - supplier
- type: directory
  path: catalogues
  label: Categories
  create: documents
  match: "**/*"
  exclude: "**/index.md"
  new_doc_ext: md
  templates:
  - catalogue
- type: heading
  label: Lists
- type: document
  path: _data/categories.yml
  label: Category list
- type: heading
  label: Documentation
- type: document
  path: _data/instructions.md
  label: Instructions
  read_only: true
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
